version: "3"

services:
  nginx:
    image: nginx
    # command: [nginx-debug, "-g", "daemon off;"]
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./nginx.error.log:/var/logs/nginx/site.error.log
    ports:
      - ${PORT:-1902}:80

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db}
      MYSQL_USER: ${MYSQL_USER:-dbuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dbpass}
    volumes:
      - db:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    env_file: .env
    volumes:
      - ./:/var/www/html
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER:-dbuser}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-dbpass}

volumes:
  db:
